import Head from "next/head";
import { useInfiniteQuery, useMutation, useQuery } from "react-query";
import { useRouter } from "next/router";
import React, { useContext, useEffect, useState } from "react";
import Navbar from "../components/molecules/NavBar";
import SingleCard from "../components/atoms/SingleCard";
import ProfileHeader from "../components/molecules/ProfileHeader";
import { getUser, getUserDecks } from "../api/user";
import { AppUiContext } from "../Context";

export default function Home({ profile }) {
  const router = useRouter();
  const [state] = useContext(AppUiContext);
  const queryKey = "profile";
  const queryValue = router.query[queryKey] || profile;
  const query = useQuery(
    ["getProfile", queryValue, state.user?.accessToken],
    getUser,
    {
      retryOnMount: true,
    }
  );
  const userDecks = useInfiniteQuery(
    ["getUserDecks", queryValue],
    getUserDecks
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar showTopBarMobile>
        {!query.isLoading && !query.error ? (
          <>
            <ProfileHeader user={query.data} />
            <div className="grid row-auto grid-cols-2 lg:m-20 sm:grid-cols-3 md:grid-cols-3 md:mx-3 lg:grid-cols-3 gap-1 sm:my-8">
              {userDecks.isLoading ? (
                <>
                  <SingleCard key={0} />
                  <SingleCard key={1} />
                  <SingleCard key={2} />
                  <SingleCard key={3} />
                  <SingleCard key={4} />
                  <SingleCard key={5} />
                </>
              ) : (
                userDecks.data.pages.map((page) => (
                  <React.Fragment key={page.nextId}>
                    {page.data.decks.map((deck) => (
                      <SingleCard deck={deck} key={deck.id} />
                    ))}
                  </React.Fragment>
                ))
              )}
            </div>
          </>
        ) : (
          <p>Error</p>
        )}
      </Navbar>
    </>
  );
}
export async function getServerSideProps(context) {
  const { profile } = context.params;
  return {
    props: {
      profile,
    },
  };
}
