import React, { useContext, useEffect, useRef } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useInfiniteQuery } from "react-query";
import { InView } from "react-intersection-observer";
import Navbar from "../components/molecules/NavBar";
import { AppUiContext } from "../Context";
import { getDecksAsAdmin } from "../apiPlugs/deck";
import { BackButton } from "../components/atoms/Icons";
import EditDeckData from "../components/molecules/EditDeckData";

export default function Home() {
  const [state] = useContext(AppUiContext);
  const pageNumber = useRef(0);
  const router = useRouter();

  const query = useInfiniteQuery(
    ["grabDecksAsAdmin", state.user?.accessToken],
    getDecksAsAdmin
  );
  useEffect(() => {
    if (!state.loggedIn) {
      router.replace("/");
    }
  }, []);
  return (
    <>
      <Head>
        <title>Swiplus Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar>
        <div className="flex items-center">
          <button
            onClick={() => router.replace(`/${state.user.userId}`)}
            type="button"
          >
            <BackButton className="text-gray-100 text-md font-inter font-bold h-10 w-10" />
          </button>
          <h3 className="text-gray-100 text-xl  font-inter font-bold w-full">
            Deck manager
          </h3>
        </div>
        <div className="grid row-auto grid-cols-1 lg:m-20  sm:grid-cols-2 md:grid-cols-2 gap-1 sm:my-8">
          {query.isLoading ? (
            <></>
          ) : (
            <>
              {query.data.pages.map((page) => (
                <React.Fragment key={page.nextId}>
                  {page.data.decks.map((project) => (
                    <EditDeckData deck={project} />
                  ))}
                </React.Fragment>
              ))}
              <InView
                as="div"
                onChange={(inView) => {
                  if (inView) {
                    // Check if data has all the decks
                    if (
                      query.data.pages[query.data.pages.length - 1].nextPage
                    ) {
                      pageNumber.current += 1;
                      query.fetchNextPage({ pageParam: pageNumber.current });
                    }
                  }
                }}
              />
            </>
          )}
        </div>
      </Navbar>
    </>
  );
}
