import { useContext, useState } from "react";
import Head from "next/head";
import Navbar from "../components/molecules/NavBar";
import { AppUiContext } from "../Context";
import SingleCard from "../components/atoms/SingleCard";

export default function Home() {
  const [state, dispatch] = useContext(AppUiContext);
  const [files, setFiles] = useState(0);
  return (
    <>
      <Head>
        <title>Swiplus Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar>
        <div className="flex justify-center">
          <div className="flex flex-col w-11/12">
            <h3 className="text-gray-100 text-4xl m-3 font-inter font-bold w-full">
              Create deck
            </h3>
            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-3 md:mx-3 lg:grid-cols-4 xl:grid-cols-5 gap-1">
              <SingleCard />
              <SingleCard />
              <SingleCard />
              <SingleCard />
              <SingleCard />
              <SingleCard />
            </div>
          </div>
        </div>
      </Navbar>
    </>
  );
}
