import Head from "next/head";
import Navbar from "../components/molecules/NavBar";
import SingleCard from "../components/atoms/SingleCard";

export default function Home() {
  return (
    <>
      <Head>
        <title>Swiplus Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar showTopBarMobile>
        <div className="grid row-auto grid-cols-2 sm:grid-cols-3 md:grid-cols-3 md:mx-3 lg:grid-cols-4 xl:grid-cols-4 gap-1 sm:my-8">
          <SingleCard />
          <SingleCard />
          <SingleCard />
          <SingleCard />
          <SingleCard />
          <SingleCard />
          <SingleCard />
          <SingleCard />
          <SingleCard />
          <SingleCard />
        </div>
      </Navbar>
    </>
  );
}
