/* eslint-disable react/jsx-props-no-spreading */
import { useContext, useEffect } from "react";
import Head from "next/head";
import { useMutation } from "react-query";
import { useRouter } from "next/router";
import { AppUiContext } from "../Context";
import { SpinnerBasic } from "../components/atoms/Icons";
import { logout } from "../apiPlugs/Auth";

export default function Home() {
  const [state, dispatch] = useContext(AppUiContext);
  const router = useRouter();

  const mutation = useMutation(logout, {
    onError: async () => {
      router.replace("/");
    },
    onSuccess: async ({ data }) => {
      dispatch({
        type: "logout-user",
      });
      router.replace("/");
    },
  });
  useEffect(() => {
    if (!state.loggedIn) {
      router.replace("/");
    }
    mutation.mutate();
  }, []);
  return (
    <>
      <Head>
        <title>Swiplus logout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen">
        <div className="m-auto  items-center flex flex-col">
          <SpinnerBasic className="animate-spin -ml-1 mr-3 h-16 w-16 text-indigo-600" />
          <p className="text-gray-100 text-xl m-3">Logging Out</p>
        </div>
      </div>
    </>
  );
}
