import React, { useContext, useRef } from "react";
import Head from "next/head";
import { useInfiniteQuery } from "react-query";
import { InView } from "react-intersection-observer";
import Navbar from "../components/molecules/NavBar";
import { AppUiContext } from "../Context";
import { grabNotifications } from "../apiPlugs/user";
import DisplayNotif from "../components/molecules/NotificationDisplay";

export default function Home() {
  const [state] = useContext(AppUiContext);
  const pageNumber = useRef(0);
  const query = useInfiniteQuery(
    ["grabNotifs", state.user.accessToken],
    grabNotifications,
    {}
  );
  return (
    <>
      <Head>
        <title>Swiplus Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar showTopBarMobile>
        <div className="p-1">
          {query.isLoading && !query.error ? (
            <></>
          ) : (
            query.data.pages.map((page) => (
              <React.Fragment key={page.nextId}>
                {page.data.data.map((project) => (
                  <DisplayNotif notifData={project} />
                ))}
              </React.Fragment>
            ))
          )}
        </div>
        {query.isLoading && !query.error ? (
          <></>
        ) : (
          <InView
            as="div"
            onChange={(inView) => {
              if (inView) {
                // Check if data has all the decks
                if (
                  query.data.pages[query.data.pages.length - 1].data.nextPage
                ) {
                  pageNumber.current += 1;
                  query.fetchNextPage({ pageParam: pageNumber.current });
                }
              }
            }}
          />
        )}
      </Navbar>
    </>
  );
}
