/* eslint-disable no-nested-ternary */
/* eslint-disable react/jsx-props-no-spreading */
/* eslint-disable jsx-a11y/click-events-have-key-events */
/* eslint-disable jsx-a11y/no-static-element-interactions */
import { useContext, useEffect, useState } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useMutation, useQuery, useQueryClient } from "react-query";
import { useForm } from "react-hook-form";
import Navbar from "../components/molecules/NavBar";
import { AppUiContext } from "../Context";
import {
  CloseIcon,
  PlusIcon,
  ArrowCircleLeft,
  ArrowCircleRight,
  SpinnerBasic,
  BackButton,
} from "../components/atoms/Icons";
import { editUser, getUser } from "../api/user";
import { changeUsername } from "../api/Auth";

export default function Home() {
  const [state, dispatch] = useContext(AppUiContext);
  const [usernameAvailable, setUsernameAvailable] = useState(true);
  const [link, setLink] = useState("");
  const [username, setUsername] = useState("");
  const [initialUsername, setInitialUsername] = useState("");
  const [displyName, setDisplayName] = useState("");
  const router = useRouter();
  const [bio, setBio] = useState("");
  const [serverError, setServerError] = useState(false);
  const queryClient = useQueryClient();
  const query = useQuery(
    ["getProfileForEditing", state.user?.userId, state.user?.accessToken],
    getUser
  );
  const userDataMutation = useMutation(editUser, {
    onSuccess: async () => {
      queryClient.invalidateQueries("getProfile");
      queryClient.invalidateQueries("getProfileForEditing");
      router.back();
    },
    onError: async () => {
      queryClient.invalidateQueries("getProfileForEditing");
      setServerError(true);
    },
  });
  const userUsernameMutation = useMutation(changeUsername, {
    onSuccess: async ({ status }) => {
      if (status === 201) {
        queryClient.invalidateQueries("getProfile");
        queryClient.invalidateQueries("getProfileForEditing");
        return router.back();
      }
      setUsernameAvailable(true);
    },
    onError: async () => {
      setUsernameAvailable(false);
    },
  });
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm();
  const checkUsernameAvailability = (text) => {
    userUsernameMutation.mutate({
      active: false,
      username: text,
      token: state.user.accessToken,
    });
  };
  const changeUsernameInitiate = () => {
    userUsernameMutation.mutate({
      active: true,
      username,
      token: state.user.accessToken,
    });
  };
  useEffect(() => {
    queryClient.invalidateQueries("getProfile");
    if (!query.isLoading) {
      setDisplayName(query.data.data.display_name);
      setLink(query.data.data.link || "");
      setBio(query.data.data.bio || "");
      setUsername(query.data.data.username || "");
      setInitialUsername(query.data.data.username || "");
    }
  }, [query.isLoading]);
  const addImages = (event) => {
    let imageFiles;
    if (event.target.files) {
      imageFiles = [...event.target.files].map((item) => {
        const itemURL = URL.createObjectURL(item);
        return { pic: itemURL, source: item };
      });
    }
    setPics((picsState) => picsState.concat(imageFiles));
  };
  const editUserData = () => {
    userDataMutation.mutate({
      name: displyName,
      bio,
      link,
      token: state.user.accessToken,
    });
  };

  return (
    <>
      <Head>
        <title>Swiplus Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar>
        <div className="flex justify-center max-w-md ">
          <div className="flex flex-col w-11/12">
            <div className="flex">
              <button onClick={() => router.back()} type="button">
                <BackButton className="text-gray-100 m-3 mt-10 font-inter font-bold h-10 w-10" />
              </button>
              <h3 className="text-gray-100 text-xl m-3 mt-10 font-inter font-bold self-center">
                Edit user
              </h3>
            </div>
            {!query.isLoading && !query.error ? (
              <>
                <form onSubmit={handleSubmit(() => editUserData())}>
                  <div className=" text-red-500  p-2 rounded-md text-sm text-left w-full">
                    {errors.displyName?.type === "required" &&
                      "Name is required"}
                    {errors.displyName?.type === "minLength" &&
                      "Name has to be more than 3 characters"}
                    {errors.displyName?.type === "maxLength" &&
                      "Name has to be less than 60 characters"}

                    {serverError
                      ? "Server error. Don't fret. Give it another shot"
                      : ""}
                    {errors.files?.type === "required" &&
                      "One or more cards are required"}
                  </div>
                  <input
                    className="bg-gray-600 mb-4  border-2 border-transparent rounded-xl w-full h-14 py-2 px-4 text-gray-100 font-inter leading-tight focus:outline-none  focus:border-blue-600"
                    id="inline-user-displayname"
                    {...register("displayName", {
                      maxLength: 60,
                      minLength: 3,
                      min: 3,
                    })}
                    type="text"
                    value={displyName}
                    onChange={(e) => setDisplayName(e.target.value)}
                    placeholder="Name"
                  />
                  <div className="flex">
                    <div className=" bg-gray-800 text-gray-400 p-4 text-center align-middle rounded-xl h-14 rounded-r-none font-bold font-inter">
                      https://
                    </div>
                    <input
                      className="bg-gray-600 mb-4 rounded-l-none  border-2 border-transparent rounded-xl w-full h-14 py-2 px-4 text-gray-100 font-inter leading-tight focus:outline-none  focus:border-blue-600"
                      id="inline-user-link"
                      {...register("link", { maxLength: 140 })}
                      type="text"
                      value={link}
                      onChange={(e) => setLink(e.target.value)}
                      placeholder="link"
                    />
                  </div>
                  <textarea
                    rows="5"
                    {...register("bio", { maxLength: 149 })}
                    value={bio}
                    onChange={(e) => setBio(e.target.value)}
                    placeholder="Bio"
                    className="bg-gray-600 mb-4  border-2 border-transparent rounded-xl w-full py-2 px-4 text-gray-100 font-inter leading-tight focus:outline-none  focus:border-blue-600"
                  />
                  <div className="w-full flex self-end mb-4">
                    <input
                      type="submit"
                      value="Submit"
                      className="bg-indigo-700 text-white text-sm font-inter font-bold  hover:bg-indigo-500 flex justify-center items-center border-2 mb-5 border-transparent rounded-full w-3/12 h-12 py-2 px-4 leading-tight focus:outline-none  focus:border-blue-600"
                    />
                  </div>
                </form>
                <form>
                  <h3 className="text-gray-100 text-xl mb-3 font-inter self-center">
                    Change username
                  </h3>
                  <div
                    className={`${
                      usernameAvailable ? "text-green-600" : "text-red-600"
                    }`}
                  >
                    {usernameAvailable && username !== initialUsername
                      ? "username available"
                      : username.length === 0
                      ? ""
                      : username === initialUsername
                      ? ""
                      : "username taken"}
                  </div>
                  <input
                    className="bg-gray-600 mb-4 border-2 border-transparent rounded-xl w-full h-14 py-2 px-4 text-gray-100 font-inter leading-tight focus:outline-none  focus:border-blue-600"
                    id="inline-user-username"
                    type="text"
                    value={username}
                    onChange={(e) => {
                      checkUsernameAvailability(e.target.value);
                      setUsername(e.target.value);
                    }}
                    placeholder="username"
                  />
                  <div className="w-full flex self-end mb-4">
                    {usernameAvailable && username !== initialUsername ? (
                      <input
                        onClick={changeUsernameInitiate}
                        type="submit"
                        value="Change username"
                        className="bg-indigo-700 text-white text-sm font-inter font-bold  hover:bg-indigo-500 flex justify-center items-center border-2 mb-5 border-transparent rounded-full w-6/12 h-12 py-2 px-4 leading-tight focus:outline-none  focus:border-blue-600"
                      />
                    ) : username.length === 0 ? (
                      <></>
                    ) : (
                      <></>
                    )}
                  </div>
                </form>
              </>
            ) : (
              <></>
            )}
          </div>
        </div>
      </Navbar>
    </>
  );
}
